<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => 'iphone 12 Pro Max',
                'price' => 11999000,
                'description' => 'Thiết kế sang trọng, hiệu năng mạnh mẽ, camera chất lượng cao.',
                'image' => 'images/products/phone/ip12pm.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 2,
                'name' => 'iPhone 13',
                'price' => 19999000,
                'description' => 'Thiết kế sang trọng, hiệu năng mạnh mẽ, camera chất lượng cao.',
                'image' => 'images/products/phone/iphone13.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 3,
                'name' => 'iPhone 14 Pro Max',
                'price' => 28999000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone14promax.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'iPhone 11 Pro Max',
                'price' => 10999000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone11promax.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'iPhone 11',
                'price' =>6999000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone11.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'iPhone 15 Pro Max',
                'price' => 25999000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone15promax.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'iPhone 16 Pro Max',
                'price' => 27999000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone16promax.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>8,
                'name' => 'iPhone 12 Pro',
                'price' => 12999000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone12pro.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>9,
                'name' => 'iPhone 12',
                'price' => 10999000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone12.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'iPhone 16',
                'price' => 20699000,
                'description' => 'Màn hình OLED sắc nét, hiệu suất tuyệt vời, pin bền bỉ.',
                'image' => 'images/products/phone/iphone16.jpg',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Laptop Asus Vivobook Go 15',
                'price' => 12690000,
                'description' => 'Laptop Asus Vivobook Go 15 E1504FA R5 7520U/16GB/512GB/Win11',
                'image' => 'images/products/ltAsus15.jpg',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Laptop MacBook Air 13',
                'price' => 26990000,
                'description' => 'Laptop MacBook Air 13 inch M4 16GB/256GB',
                'image' => 'images/products/ltMac13.jpg',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Laptop MSI Gaming Thin 15',
                'price' => 15690000,
                'description' => 'Laptop MSI Gaming Thin 15 B12UCX i5 12450H/16GB/512GB/4GB RTX2050/144Hz/Win11',
                'image' => 'images/products/ltMSI15.jpg',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Laptop MSI Modern 15 F13MG',
                'price' => 14190000,
                'description' => 'Laptop MSI Modern 15 F13MG i5 1335U/16GB/512GB/Win11',
                'image' => 'images/products/ltMSI15F13.jpg',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Laptop Acer Aspire 7',
                'price' => 13990000,
                'description' => 'Laptop Acer Aspire 7 A715 76 53PJ i5 12450H/16GB/512GB/Win11',
                'image' => 'images/products/ltAcer7.jpg',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Apple Watch Series 9',
                'price' => 9990000,
                'description' => 'Apple Watch Series 9 GPS + Cellular 45mm Viền nhôm Dây cao su cỡ S/M',
                'image' => 'images/products/awS9.jpg',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Apple Watch Series 10',
                'price' =>8320000,
                'description' => 'Apple Watch Series 10 42mm (GPS) Viền Nhôm Dây Cao Su Size S/M | Chính hãng Apple Việt Nam',
                'image' => 'images/products/awS10.jpg',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Apple Watch Ultra 2',
                'price' => 22390000,
                'description' => 'Apple Watch Ultra 2 2024 49mm 4G Viền Titan Dây Titan Size M | Chính hãng VN/A',
                'image' => 'images/products/awU2.jpg',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Apple Watch SE 2',
                'price' => 5820000,
                'description' => 'Apple Watch SE 2 2024 44mm (GPS) Viền Nhôm Dây Cao Su Size M/L',
                'image' => 'images/products/awSE2.jpg',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Apple Watch Series 10',
                'price' => 20699000,
                'description' => 'Apple Watch Series 10 46mm (GPS) Viền Nhôm Dây Cao Su Size M/L | Chính hãng Apple Việt Nam',
                'image' => 'images/products/awS10.jpg',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Apple AirPods 4',
                'price' => 3090000,
                'description' => 'Tai nghe Bluetooth Apple AirPods 4 | Chính hãng Apple Việt Nam',
                'image' => 'images/products/apPro4.jpg',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => ' Apple AirPods Max 2024',
                'price' => 12290000,
                'description' => 'Tai nghe chụp tai chống ồn Apple AirPods Max 2024 | Chính hãng Apple Việt Nam',
                'image' => 'images/products/apMax4.jpg',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Apple AirPods 2',
                'price' => 2090000,
                'description' => 'Tai nghe Bluetooth Apple AirPods 2 | Chính hãng Apple Việt Nam',
                'image' => 'images/products/apPro4.jpg',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Apple EarPods Lightning',
                'price' => 500000,
                'description' => 'Tai nghe Apple EarPods Lightning MWTY3ZA/A | Chính hãng Apple Việt Nam',
                'image' => 'images/products/apL.jpg',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Apple AirPods Max',
                'price' => 8990000,
                'description' => 'Tai nghe chụp tai chống ồn Apple AirPods Max 2024 | Chính hãng Apple Việt Nam',
                'image' => 'images/products/apMax.jpg',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Kính cường lực Iphone 14 Pro Max',
                'price' => 8990000,
                'description' => 'Kính cường lực KingKong',
                'image' => 'images/products/KCL.jpg',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}